nelmio_api_doc:
    documentation:
        info:
            title: Api bilemo
            description: Une API BtoB offrant un catalogue de telephones aux opérateurs mobiles
            version: 2.0.0
        paths:
            /api/login_check:
                post:
                    tags:
                        - Token
                    operationId: postCredentialsItem
                    summary: Permet d'obtenir le token JWT pour se logger.
                    requestBody:
                        description: Crée un nouveau token JWT
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Récupère le token JWT
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'

            /api/users:
                get:
                    summary: Permet d'obtenir la liste des utilisateurs de tout les opérateurs.

            # /api/customers/{id}/users:
            #     post:
            #         tags:
            #             - Users
            #         summary: Permet de créer un nouvel utilisateur pour un opérateur.
            #         requestBody:
            #             content:
            #                 application/json:
            #                     schema:
            #                         type: object
            #                         properties:
            #                             firstName:
            #                                 type: string
            #                             lastName:
            #                                 type: string
            #                             email:
            #                                 type: string



        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: admin@Orangeapi.com
                        password:
                            type: string
                            default: admin
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        # disable_default_routes: true    

        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
